OBJS += passes/rfuzz/assert_probes.o
OBJS += passes/rfuzz/mark_resets.o
OBJS += passes/rfuzz/meta_reset.o
OBJS += passes/rfuzz/mux_probes.o
OBJS += passes/rfuzz/port_assert_probes.o
OBJS += passes/rfuzz/port_fuzzing_inputs.o
OBJS += passes/rfuzz/port_mux_probes.o
